"""Bootstrap helpers for ``wayfinder-router init`` / ``doctor``.

Pure scaffolding to get started fast: render a starter ``wayfinder-router.toml`` from
a preset, a matching ``.env.example`` (env-var *names* only — never a secret), and
report whether each model's key resolves from the environment.

Wayfinder reads keys from the environment at request time and never stores them
(WF-ADR-0004); these helpers only ever name the variables. Lives in the invocation
layer; the deterministic core is untouched (WF-ADR-0001).
"""

from __future__ import annotations

import os
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # type-only: avoid importing the gateway for a duck-typed attr read
    from collections.abc import Mapping, MutableMapping

    from .gateway import GatewayModel

# How long to wait on a key-resolution command (WF-DESIGN-0006) — generous enough
# for an interactive vault unlock (e.g. a 1Password biometric prompt).
KEY_CMD_TIMEOUT = 30.0

# Injected I/O for the interactive wizard, so the logic stays pure and testable
# (mirrors onboard.py). ``ask(prompt, default) -> answer``; ``say(msg)`` narrates.
Ask = Callable[[str, str], str]
Say = Callable[[str], None]


@dataclass(frozen=True)
class Preset:
    """A named starter configuration: the toml to write and the env vars it needs."""

    name: str
    summary: str
    config_toml: str
    env_vars: tuple[str, ...]


# The hybrid preset: a keyless local Ollama arm and an Anthropic cloud arm. It best
# shows the local-vs-cloud value and the keyless path; tune or swap endpoints freely.
_HYBRID_TOML = """\
# wayfinder-router.toml — generated by `wayfinder-router init` (preset: hybrid).
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

[routing]
# Structural cut: prompts scoring below this stay on the local arm; at or above it
# they escalate to cloud. Tune with `wayfinder-router calibrate`, or /threshold in chat.
threshold = 0.08

# Local arm — Ollama (OpenAI-compatible, keyless). Start it with `ollama serve`,
# then pull the model: `ollama pull llama3.1`.
[gateway.models.local]
base_url = "http://localhost:11434/v1"
model = "llama3.1"
cost_per_1k = 0.0   # local inference is free; used for the chat's savings estimate

# Cloud arm — Anthropic. The key is read from $ANTHROPIC_API_KEY at request time;
# it is never written here. `export ANTHROPIC_API_KEY=...` before running.
[gateway.models.cloud]
base_url = "https://api.anthropic.com/v1"
model = "claude-sonnet-4-6"
api_key_env = "ANTHROPIC_API_KEY"
# Prefer not to `export` a raw key? Fill it from your secret store at startup instead
# (held in memory only, never written to disk). `wayfinder-router doctor` suggests a line:
# api_key_cmd = "op read op://Private/Anthropic/credential"   # 1Password / Keychain / pass / …
cost_per_1k = 0.009   # rough $/1k tokens (blended) — edit for your pricing

# Prefer Google Gemini for the cloud arm? Gemini speaks OpenAI's /chat/completions at
# its compat base_url, so it drops straight in — swap the [gateway.models.cloud] block
# above for the one below (key read from $GEMINI_API_KEY at request time, never stored):
# [gateway.models.cloud]
# base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
# model = "gemini-2.5-flash"
# api_key_env = "GEMINI_API_KEY"
# cost_per_1k = 0.0003   # rough $/1k tokens (blended) — edit for your pricing
"""

# The openai preset: one provider, two cost tiers (a small fast model and a large
# capable one). Both arms read the same OPENAI_API_KEY. Tier names are cost labels,
# not locations — there is no on-device arm here.
_OPENAI_TOML = """\
# wayfinder-router.toml — generated by `wayfinder-router init --preset openai`.
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

# Two cost tiers from one provider: prompts scoring below the cut use the small model;
# at or above it they escalate to the large one. Tune cuts with `wayfinder-router calibrate`.
[[routing.tiers]]
min_score = 0.0
model = "small"

[[routing.tiers]]
min_score = 0.08
model = "large"

# Small (cheap) arm.
[gateway.models.small]
base_url = "https://api.openai.com/v1"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"
cost_per_1k = 0.0004   # rough $/1k tokens (blended) — edit for your pricing

# Large (capable) arm — same key, read from the environment at request time.
[gateway.models.large]
base_url = "https://api.openai.com/v1"
model = "gpt-4o"
api_key_env = "OPENAI_API_KEY"
cost_per_1k = 0.0075   # rough $/1k tokens (blended) — edit for your pricing
"""

# The gemini preset: two cost tiers from Google Gemini via its OpenAI-compatible endpoint
# (Flash → Pro). Both arms read the same GEMINI_API_KEY. Like `openai`, tier names are
# cost labels, not locations — there is no on-device arm here.
_GEMINI_TOML = """\
# wayfinder-router.toml — generated by `wayfinder-router init --preset gemini`.
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

# Two cost tiers from Google Gemini: prompts scoring below the cut use Flash; at or above
# it they escalate to Pro. Tune cuts with `wayfinder-router calibrate`.
[[routing.tiers]]
min_score = 0.0
model = "flash"

[[routing.tiers]]
min_score = 0.08
model = "pro"

# Flash (cheap, fast) arm. Gemini speaks OpenAI's /chat/completions at this base_url; the
# key is read from $GEMINI_API_KEY at request time and is never written here.
[gateway.models.flash]
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
model = "gemini-2.5-flash"
api_key_env = "GEMINI_API_KEY"
cost_per_1k = 0.0003   # rough $/1k tokens (blended) — edit for your pricing

# Pro (capable) arm — same key, read from the environment at request time.
[gateway.models.pro]
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
model = "gemini-2.5-pro"
api_key_env = "GEMINI_API_KEY"
cost_per_1k = 0.005   # rough $/1k tokens (blended) — edit for your pricing
"""

DEFAULT_PRESET = "hybrid"

PRESETS: dict[str, Preset] = {
    "hybrid": Preset(
        name="hybrid",
        summary="keyless local Ollama → Anthropic cloud",
        config_toml=_HYBRID_TOML,
        env_vars=("ANTHROPIC_API_KEY",),
    ),
    "openai": Preset(
        name="openai",
        summary="OpenAI two-tier (gpt-4o-mini → gpt-4o)",
        config_toml=_OPENAI_TOML,
        env_vars=("OPENAI_API_KEY",),
    ),
    "gemini": Preset(
        name="gemini",
        summary="Gemini two-tier (gemini-2.5-flash → gemini-2.5-pro)",
        config_toml=_GEMINI_TOML,
        env_vars=("GEMINI_API_KEY",),
    ),
}


# The macOS Keychain read used by `init --keychain` (WF-ADR-0044): the desktop app stores the
# key under service "wayfinder-router" / account "<ENV_VAR>", and the gateway reads it back at
# startup through this command — the key itself never lands in the config file (WF-ADR-0004).
_KEYCHAIN_CMD = '/usr/bin/security find-generic-password -s wayfinder-router -a {env} -w'


def keychain_api_key_cmd(env: str) -> str:
    """The `api_key_cmd` string reading ``env``'s key from the macOS Keychain — the one seam
    reference every Keychain-backed model (init's `--keychain`, `config add-model --keychain`)
    is built from, so there is exactly one place that knows this command's shape."""
    return _KEYCHAIN_CMD.format(env=env)


def render_config(preset: Preset, keychain: bool = False) -> str:
    """The ``wayfinder-router.toml`` scaffold for ``preset`` (loads back unchanged).

    With ``keychain=True`` (macOS; `init --keychain`), every **uncommented** ``api_key_env``
    line gains an ``api_key_cmd`` reading that env var's key from the macOS Keychain — the seam
    the desktop app scaffolds through (WF-ADR-0044). Commented example blocks stay untouched,
    and ``keychain=False`` returns the template byte-for-byte unchanged.
    """
    if not keychain:
        return preset.config_toml
    out: list[str] = []
    for line in preset.config_toml.splitlines(keepends=True):
        out.append(line)
        stripped = line.strip()
        if stripped.startswith("api_key_env"):
            env = stripped.split("=", 1)[1].strip().strip('"')
            cmd = _KEYCHAIN_CMD.format(env=env)
            out.append(f'api_key_cmd = "{cmd}"   # macOS Keychain (the desktop app stores this item)\n')
    return "".join(out)


def render_env_example(preset: Preset) -> str:
    """A ``.env.example`` with the preset's env-var *names* only — never a secret."""
    lines = [
        "# Wayfinder model keys — export these in your shell (e.g. via direnv or dotenv).",
        "# Wayfinder reads them at request time and never writes secrets to disk.",
        "# Leave a value blank to rely on the keyless local arm only.",
        "",
    ]
    lines += [f"{name}=" for name in preset.env_vars]
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class KeyStatus:
    """Whether one model's key resolves: the env-var name and whether it is set."""

    name: str  # the gateway model name (the routing target)
    model: str  # the upstream model id
    base_url: str
    env_var: str | None  # the env var holding the key, or None for a keyless arm
    ok: bool  # keyless, or the named var is set
    cmd: str | None = None  # command that fills env_var when unset (WF-DESIGN-0006), if any


def key_status(models: Mapping[str, GatewayModel]) -> list[KeyStatus]:
    """Report each model's key readiness — the same rule the gateway uses (key from env).

    A pure read of the environment; it never runs an ``api_key_cmd``. Call
    :func:`resolve_keys` first if you want command-filled keys reflected here.
    """
    statuses: list[KeyStatus] = []
    for name, model in models.items():
        env_var = model.api_key_env
        ok = env_var is None or bool(os.environ.get(env_var))
        statuses.append(
            KeyStatus(
                name=name,
                model=model.model,
                base_url=model.base_url,
                env_var=env_var,
                ok=ok,
                cmd=getattr(model, "api_key_cmd", None),
            )
        )
    return statuses


def missing_keys(statuses: list[KeyStatus]) -> list[str]:
    """Distinct env-var names that are named but unset (sorted, deduped)."""
    return sorted({s.env_var for s in statuses if s.env_var and not s.ok})


# --- secure key resolution (WF-DESIGN-0006) ---------------------------------
class KeyResolutionError(Exception):
    """An ``api_key_cmd`` failed to produce a key (non-zero exit, timeout, empty)."""


def _run_key_cmd(cmd: str) -> str:
    """Run ``cmd`` in a shell and return its stdout (the key), stripped.

    ``shell=True`` so users can write the same line their secret tool documents
    (``op read op://...``, ``security find-generic-password -w ...``). The command
    comes from the user's own config, so it runs with their privileges — the same
    trust as a line they would type to ``export`` the key themselves. stderr is
    inherited so an interactive unlock prompt still reaches the terminal; only
    stdout (the secret) is captured, and it is never logged.
    """
    import subprocess

    try:
        proc = subprocess.run(  # noqa: S602 - shell intentional; command is user-authored
            cmd, shell=True, stdout=subprocess.PIPE, text=True, timeout=KEY_CMD_TIMEOUT
        )
    except subprocess.TimeoutExpired as exc:
        raise KeyResolutionError(f"timed out after {KEY_CMD_TIMEOUT:g}s: {cmd}") from exc
    except OSError as exc:
        raise KeyResolutionError(f"could not run command: {exc}") from exc
    if proc.returncode != 0:
        raise KeyResolutionError(f"command exited {proc.returncode}: {cmd}")
    return (proc.stdout or "").strip()


def resolve_keys(
    models: Mapping[str, GatewayModel],
    *,
    environ: MutableMapping[str, str] | None = None,
    runner: Callable[[str], str] | None = None,
) -> dict[str, str]:
    """Fill each model's ``api_key_env`` from its ``api_key_cmd`` when the var is unset.

    Runs the user's command (e.g. ``op read op://Private/Anthropic/key``) and loads
    the result into the process environment **in memory only** — the secret is never
    written to config or disk. An env var that is already set always wins (CI, an
    explicit ``export``), so the command runs only when needed and is never required.

    Returns a ``{model_name: error_message}`` map for commands that failed (empty when
    everything resolved or had nothing to do). Errors carry the *command*, never a key.
    """
    env = os.environ if environ is None else environ
    run = _run_key_cmd if runner is None else runner
    errors: dict[str, str] = {}
    for name, model in models.items():
        cmd = getattr(model, "api_key_cmd", None)
        var = model.api_key_env
        if not cmd or not var or env.get(var):
            continue  # keyless, no command, or the key is already present
        try:
            value = run(cmd).strip()  # normalize here so any runner is treated alike
        except KeyResolutionError as exc:
            errors[name] = str(exc)
            continue
        if not value:
            errors[name] = f"command produced no output: {cmd}"
            continue
        env[var] = value  # in-process only; never persisted
    return errors


# Secret tools we can recommend an `api_key_cmd` for, in preference order. Each maps
# a detected executable to a fill-in-the-blank command the user can paste and adjust.
# The resolver runs *any* command; this list only drives the friendly suggestions.
_KEY_HELPERS: tuple[tuple[str, str, str], ...] = (
    # NOTE: single-quote any inner literals so the line stays a valid double-quoted
    # TOML value (`api_key_cmd = "<cmd>"`) when copy-pasted — guarded by a test.
    ("op", "1Password", "op read 'op://Private/{var}/credential'"),
    ("security", "macOS Keychain", "security find-generic-password -w -s '{var}'"),
    ("secret-tool", "Linux Secret Service", "secret-tool lookup service '{var}'"),
    ("pass", "pass", "pass show {var}"),
    ("gopass", "gopass", "gopass show -o {var}"),
    ("vault", "HashiCorp Vault", "vault kv get -field={var} secret/wayfinder"),
    (
        "aws",
        "AWS Secrets Manager",
        "aws secretsmanager get-secret-value --secret-id {var} "
        "--query SecretString --output text",
    ),
    ("bw", "Bitwarden", "bw get password {var}"),
    ("doppler", "Doppler", "doppler secrets get {var} --plain"),
    ("gcloud", "Google Secret Manager", "gcloud secrets versions access latest --secret={var}"),
)


def suggest_key_commands(env_var: str, *, which: Callable[[str], str | None] | None = None) -> list[str]:
    """Example ``api_key_cmd`` lines for the secret tools found on ``PATH``.

    Lets ``init`` / ``doctor`` point at *your* password manager instead of telling
    everyone to ``export`` a raw secret. Returns one ready-to-edit command per detected
    tool (empty if none are installed). Never runs anything — pure ``PATH`` detection.
    """
    if which is None:
        from shutil import which as _which

        which = _which
    out: list[str] = []
    for exe, _label, template in _KEY_HELPERS:
        if which(exe):
            out.append(template.format(var=env_var))
    return out


# --- interactive wizard ------------------------------------------------------
@dataclass(frozen=True)
class Provider:
    """A known upstream: its base URL, the env var it reads, and an example model."""

    key: str
    label: str
    base_url: str
    api_key_env: str | None
    example_model: str


# Custom is last so its menu number is stable; it carries placeholder defaults so no
# field is ever required (avoids re-prompt loops on EOF / piped input).
PROVIDER_CHOICES: tuple[Provider, ...] = (
    Provider("ollama", "Ollama — local, keyless", "http://localhost:11434/v1", None, "llama3.1"),
    Provider("openai", "OpenAI", "https://api.openai.com/v1", "OPENAI_API_KEY", "gpt-4o-mini"),
    Provider(
        "anthropic", "Anthropic", "https://api.anthropic.com/v1", "ANTHROPIC_API_KEY",
        "claude-sonnet-4-6",
    ),
    Provider("custom", "Custom (any OpenAI-compatible endpoint)", "http://localhost:8000/v1",
             None, "your-model"),
)

_DEFAULT_CUTS = (0.08, 0.30, 0.60, 0.80)


@dataclass(frozen=True)
class ModelArm:
    """One routing tier: a named upstream and the score at which it takes over."""

    name: str
    base_url: str
    model: str
    api_key_env: str | None
    min_score: float


def _default_tier_name(index: int) -> str:
    return {0: "local", 1: "cloud"}.get(index, f"tier{index + 1}")


def _default_cut(index: int) -> float:
    """Default escalation score for tier ``index`` (>=1; the first tier is always 0.0)."""
    return _DEFAULT_CUTS[min(index - 1, len(_DEFAULT_CUTS) - 1)]


def _slug(name: str, fallback: str) -> str:
    """A TOML-key-safe model name (the routing target); falls back if it empties out."""
    cleaned = "".join(c if (c.isalnum() or c in "-_") else "-" for c in name.strip().lower())
    return cleaned.strip("-") or fallback


def _collect_arm(ask: Ask, say: Say, index: int) -> ModelArm:
    say("")
    say(f"Tier {index + 1}:")
    for i, provider in enumerate(PROVIDER_CHOICES, start=1):
        say(f"  {i}) {provider.label}")
    choice = ask(f"  provider (1-{len(PROVIDER_CHOICES)})", "1")
    try:
        provider = PROVIDER_CHOICES[int(choice) - 1]
    except (ValueError, IndexError):
        provider = PROVIDER_CHOICES[0]

    base_url = provider.base_url
    api_key_env = provider.api_key_env
    if provider.key == "custom":
        base_url = ask("  base_url", provider.base_url)
        api_key_env = ask("  API key env var (blank = keyless)", "") or None
    model = ask("  model id", provider.example_model)
    name = _slug(ask("  name for this tier", _default_tier_name(index)), _default_tier_name(index))

    if index == 0:
        min_score = 0.0  # the base tier always starts at zero
    else:
        raw = ask("  escalate to this tier at score (0-1)", f"{_default_cut(index):g}")
        try:
            min_score = max(0.0, min(1.0, float(raw)))
        except ValueError:
            min_score = _default_cut(index)
    return ModelArm(name=name, base_url=base_url, model=model, api_key_env=api_key_env,
                    min_score=min_score)


def run_init_wizard(ask: Ask, say: Say) -> Preset:
    """Interactively assemble a multi-tier config; never captures a secret, only env names."""
    say("Let's configure your models — Wayfinder routes cheap → capable.")
    say("Keys are read from the environment at request time and are never stored here.")
    arms: list[ModelArm] = []
    while True:
        arms.append(_collect_arm(ask, say, index=len(arms)))
        if ask("Add another model tier? (y/N)", "n").strip().lower() not in {"y", "yes"}:
            break
    return _preset_from_arms(arms)


def _preset_from_arms(arms: list[ModelArm]) -> Preset:
    env_vars = tuple(sorted({a.api_key_env for a in arms if a.api_key_env}))
    plural = "s" if len(arms) != 1 else ""
    return Preset(
        name="custom",
        summary=f"{len(arms)} tier{plural} (interactive)",
        config_toml=render_config_from_arms(arms),
        env_vars=env_vars,
    )


def render_config_from_arms(arms: list[ModelArm]) -> str:
    """Render a ``wayfinder-router.toml`` from ordered arms (loads back unchanged)."""
    arms = sorted(arms, key=lambda a: a.min_score)
    out = [
        "# wayfinder-router.toml — generated by `wayfinder-router init --interactive`.",
        "#",
        "# Wayfinder never stores secrets: a model names an env var (api_key_env) and the",
        "# key is read from your environment at request time (WF-ADR-0004). Tune the score",
        "# cuts below by hand or with `wayfinder-router calibrate`.",
        "",
    ]
    for arm in arms:  # ordered score bands (WF-ADR-0002)
        out += ["[[routing.tiers]]", f"min_score = {arm.min_score:g}", f'model = "{arm.name}"', ""]
    for arm in arms:
        out += [f"[gateway.models.{arm.name}]", f'base_url = "{arm.base_url}"',
                f'model = "{arm.model}"']
        if arm.api_key_env:
            out.append(f'api_key_env = "{arm.api_key_env}"')
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"
