"""Bootstrap helpers for ``wayfinder-router init`` / ``doctor``.

Pure scaffolding to get started fast: render a starter ``wayfinder-router.toml`` from
a preset, a matching ``.env.example`` (env-var *names* only — never a secret), and
report whether each model's key resolves from the environment.

Wayfinder reads keys from the environment at request time and never stores them
(WF-ADR-0004); these helpers only ever name the variables. Lives in the invocation
layer; the deterministic core is untouched (WF-ADR-0001).
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # type-only: avoid importing the gateway for a duck-typed attr read
    from collections.abc import Mapping

    from .gateway import GatewayModel


@dataclass(frozen=True)
class Preset:
    """A named starter configuration: the toml to write and the env vars it needs."""

    name: str
    summary: str
    config_toml: str
    env_vars: tuple[str, ...]


# The hybrid preset: a keyless local Ollama arm and an Anthropic cloud arm. It best
# shows the local-vs-cloud value and the keyless path; tune or swap endpoints freely.
_HYBRID_TOML = """\
# wayfinder-router.toml — generated by `wayfinder-router init` (preset: hybrid).
#
# Wayfinder never stores secrets: a model names an env var (api_key_env) and the key
# is read from your environment at request time (WF-ADR-0004). Edit this file freely;
# re-run `wayfinder-router doctor` to check your setup.

[routing]
# Structural cut: prompts scoring below this stay on the local arm; at or above it
# they escalate to cloud. Tune with `wayfinder-router calibrate`, or /threshold in chat.
threshold = 0.08

# Local arm — Ollama (OpenAI-compatible, keyless). Start it with `ollama serve`,
# then pull the model: `ollama pull llama3.1`.
[gateway.models.local]
base_url = "http://localhost:11434/v1"
model = "llama3.1"

# Cloud arm — Anthropic. The key is read from $ANTHROPIC_API_KEY at request time;
# it is never written here. `export ANTHROPIC_API_KEY=...` before running.
[gateway.models.cloud]
base_url = "https://api.anthropic.com/v1"
model = "claude-sonnet-4-6"
api_key_env = "ANTHROPIC_API_KEY"
"""

DEFAULT_PRESET = "hybrid"

PRESETS: dict[str, Preset] = {
    "hybrid": Preset(
        name="hybrid",
        summary="keyless local Ollama → Anthropic cloud",
        config_toml=_HYBRID_TOML,
        env_vars=("ANTHROPIC_API_KEY",),
    ),
}


def render_config(preset: Preset) -> str:
    """The ``wayfinder-router.toml`` scaffold for ``preset`` (loads back unchanged)."""
    return preset.config_toml


def render_env_example(preset: Preset) -> str:
    """A ``.env.example`` with the preset's env-var *names* only — never a secret."""
    lines = [
        "# Wayfinder model keys — export these in your shell (e.g. via direnv or dotenv).",
        "# Wayfinder reads them at request time and never writes secrets to disk.",
        "# Leave a value blank to rely on the keyless local arm only.",
        "",
    ]
    lines += [f"{name}=" for name in preset.env_vars]
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class KeyStatus:
    """Whether one model's key resolves: the env-var name and whether it is set."""

    name: str  # the gateway model name (the routing target)
    model: str  # the upstream model id
    base_url: str
    env_var: str | None  # the env var holding the key, or None for a keyless arm
    ok: bool  # keyless, or the named var is set


def key_status(models: Mapping[str, GatewayModel]) -> list[KeyStatus]:
    """Report each model's key readiness — the same rule the gateway uses (key from env)."""
    statuses: list[KeyStatus] = []
    for name, model in models.items():
        env_var = model.api_key_env
        ok = env_var is None or bool(os.environ.get(env_var))
        statuses.append(
            KeyStatus(name=name, model=model.model, base_url=model.base_url, env_var=env_var, ok=ok)
        )
    return statuses


def missing_keys(statuses: list[KeyStatus]) -> list[str]:
    """Distinct env-var names that are named but unset (sorted, deduped)."""
    return sorted({s.env_var for s in statuses if s.env_var and not s.ok})
